# Generated by Django 5.0.6 on 2024-07-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMascotaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=15),
        ),
    ]
