# Generated by Django 5.0.6 on 2024-07-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMascotaApp', '0002_alter_usuario_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProd', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('foto', models.ImageField(default='fotos/default.png', upload_to='fotos')),
            ],
        ),
    ]
