# Generated by Django 5.0.6 on 2024-07-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMascotaApp', '0004_producto_cantidad_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
