# Generated by Django 5.0.6 on 2024-07-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMascotaApp', '0005_producto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='Cliente', max_length=20),
        ),
    ]
