# Generated by Django 5.0.6 on 2024-07-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMascotaApp', '0007_alter_usuario_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreProd',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
